### PR TITLE
Make jmx public

### PR DESCRIPTION
**Pull request by MALPI**
Since we are integrating cassandra-reaper we need to have this ports accessible from remote. Furthermore JMX is already accessible from remote on the 2.x branch.

### CODE REVIEW

**Comment by vroldanbet** [comment]
:+1:

**Comment by lmineiro** [comment]
Does this mean it will be accessible on the public Elastic IPs ?

**Comment by MALPI** [comment]
No, I didn't touch the security groups. If one does, this probably is possible. You have anything else in mind?

The branch naming is quite bad. Sorry.

**Comment by MALPI** [comment]
@lmineiro any update?

**Comment by lmineiro** [comment]
👍

**Pull request merged**
