### PR TITLE
Release new versions + use new base image

### PR DESCRIPTION
**Pull request by a1exsh**
Use openjdk-8 base image and bump versions to the latest releases.

### CODE REVIEW

**Comment by slitsche** [comment]
:+1:

**Comment by avaczi** [comment]
No breaking changes in those minor version upgrades?

**Comment by a1exsh** [comment]
@avaczi not that I'm aware of, but anyone who is upgrading should check the release notes for themselves :1st_place_medal:

**Comment by a1exsh** [comment]
:+1:

**Pull request merged**
