### PR TITLE
Create a custom superuser instead of using the default 'cassandra'

### LINKED ISSUE #142: Don't use default superuser
Using the default superuser named `cassandra` has some documented drawbacks, i.e: it requires quorum of nodes to verify the password (and this username is easily guessable).

### PR DESCRIPTION
**Pull request by a1exsh**
Fixes #142

### CODE REVIEW

**Comment by a1exsh** [comment]
Version 2.1 only for now.  We should think about using the same `planb-cassandra.sh` file for all versions, currently the code gets duplicated in every Docker dir.

**Comment by slitsche** [comment]
From 2.2 `create user` is deprecated.

**Comment by slitsche** [comment]
👍

**Comment by a1exsh** [comment]
Good to know about 2.2.

**Comment by a1exsh** [comment]
:+1:

**Pull request merged**
