### PR TITLE
Add TimeWindowCompactionStrategy for version 2.1 as an external jar

### PR DESCRIPTION
**Pull request by a1exsh**
Built from:
  https://github.com/jeffjirsa/twcs/
  @f6326a60746d4d5e01ba565427dd46de3df37806

### CODE REVIEW

**Comment by a1exsh** [comment]
:+1:

**Comment by avaczi** [comment]
:+1:

**Comment by a1exsh** [comment]
Wait, we've decided to build the jar inside the Dockerfile.

**Comment by avaczi** [comment]
:+1:

**Comment by slitsche** [comment]
👍

**Pull request merged**
