### PR TITLE
Root out AppDynamics for newly created cluster

### PR DESCRIPTION
**Pull request by a1exsh**
The idea of using it for Cassandra log shipping didn't prove helpful, let's
not create at least the new clusters with that thing.

### CODE REVIEW

**Comment by avaczi** [comment]
:+1:

**Comment by a1exsh** [comment]
:+1:

**Comment by slitsche** [comment]
👍

**Comment by a1exsh** [comment]
This whole 'branch is outdated' business is quite annoying...  Please +1 again ;)

**Comment by slitsche** [comment]
👍

**Comment by a1exsh** [comment]
:+1:

**Pull request merged**
