### PR TITLE
Specify exact Cassandra package version to install in Dockerfile(s)

### LINKED ISSUE #135: Specify exact version of Cassandra package to install in Dockerfile(s)
Currently we do this only for 2.1.  Other Dockerfile versions install the latest minor release.  This can lead to changing multiple things at a time w/o the intent (e.g. merge unrelated change -- get a different server version at the same time).

### PR DESCRIPTION
**Pull request by a1exsh**
Now for 3.0 and 3.x as well.
Fix #135.

### CODE REVIEW

**Comment by slitsche** [comment]
👍

**Comment by a1exsh** [comment]
This 'update branch' thingy is getting really annoying.  Need another +1 please :(

**Comment by a1exsh** [comment]
:+1:

**Comment by slitsche** [comment]
👍

**Pull request merged**
