### PR TITLE
Allow instance type to be upgraded

### PR DESCRIPTION
**Pull request by lorenzhawkes**
Add new command line option --instance-type to the update command
Fix documentation to allow the update options table to be rendered

### CODE REVIEW

**Comment by a1exsh** [comment]
:+1:

**Comment by slitsche** [comment]
Hi @lorenzhawkes 
would you please so kind to include your changes in the test for `build_run_instances_params`?

See https://github.com/zalando/planb-cassandra/blob/master/tests/test_update_cluster.py#L27

Thank you

Stefan

**Comment by lorenzhawkes** [comment]
The test case has been updated

**Comment by a1exsh** [comment]
:+1:

**Comment by slitsche** [comment]
👍

**Pull request merged**
