### PR TITLE
Some syntax needs python 3.5

### PR DESCRIPTION
**Pull request by tmuehl**
...and the create_cluster file is named with and underscore instead a dash.

### CODE REVIEW

**Comment by hjacobs** [comment]
@a1exsh actually having `--cluster-name` as an option makes no sense as it is mandatory, can we change it in the script to be an argument?

**Comment by a1exsh** [comment]
@hjacobs there was a reason to move it from the arguments to options (a required one, though).  I don't recall it at this moment, we can reconsider.  The script is destined for some more refactoring when we will be adding scale up/down, commands anyway.

**Comment by tmuehl** [comment]
@a1exsh  So I revert the changes to `create_cluster.py` again and change the readme to have it as an option parameter?

**Comment by a1exsh** [comment]
@tmuehl let me think :-)

**Comment by tmuehl** [comment]
Closed because this commit back-and-forth is getting messy. Create a new PR.

**Pull request closed without merging**
