### PR TITLE
Enable enhanced CloudWatch metrics in Taupage

### LINKED ISSUE #16: Collect enhanced CloudWatch metrics for monitoring
Should be a simple Taupage config change + something to enable the IAM policy.

### PR DESCRIPTION
**Pull request by a1exsh**
This requires setting up an IAM Instance Profile (which requires a
Role, which in turn requires a Policy).

The IAM stuff is global, and replicated across the AWS regions with
eventual consistency.  Beware of run_instances() complaining about
invalid Instance Profile ARN.  We "fix" that with a simple sleep for
30 seconds.

Fixes #16

### CODE REVIEW

**Comment by hjacobs** [comment]
Do we really need this? I never used the "enhanced CloudWatch metrics" and usually just use Prometheus (port 9100) which provides more details anyway. Another reason: CloudWatch metrics costs money (not much, but anyway).

**Comment by a1exsh** [comment]
Well, I was going to use it to enable zmon alert on DiskSpaceUtilization
metric. I've no idea about Prometheus.

**Comment by hjacobs** [comment]
@a1exsh the Prometheus Node Exporter exposes much more detailed metrics including memory and diskspace. 

Example ZMON check definition:

```python
def check():
    p = http(':9100/metrics').prometheus()
    data = {}

    # disk space
    pfree = p['node_filesystem_free']
    psize = p['node_filesystem_size']
    pfree_sum = sum([x[1] for x in pfree if x[0]["device"] == "rootfs"])
    psize_sum = sum([x[1] for x in psize if x[0]["device"] == "rootfs"])
    data['usage_percentage'] = round(100 - (pfree_sum / psize_sum * 100), 2)

    # inodes
    ifree = p['node_filesystem_files_free']
    icount = p['node_filesystem_files']
    ifree_sum = sum([x[1] for x in ifree if x[0]["device"] == "rootfs"])
    icount_sum = sum([x[1] for x in icount if x[0]["device"] == "rootfs"])
    data['inodes_percentage'] = round(100 - (ifree_sum / icount_sum * 100), 2)

    return data
```

See also our internal ZMON alert definition with ID 7049.

**Comment by a1exsh** [comment]
:facepalm:

**Pull request closed without merging**
